import { Food } from '../types/nutrition';
import { v4 as uuidv4 } from 'uuid';

export const starterFoods: Food[] = [
  {
    id: uuidv4(),
    name: 'Rolled Oats',
    category: 'Grains',
    baseUnit: 'g',
    macrosPer100: {
      calories: 389,
      protein: 16.9,
      carbs: 66.3,
      fat: 6.9,
      fiber: 10.6,
    },
    defaultServing: {
      quantity: 1,
      unit: 'cup',
      grams: 80,
    },
  },
  {
    id: uuidv4(),
    name: 'Chicken Breast',
    category: 'Protein',
    baseUnit: 'g',
    macrosPer100: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      fiber: 0,
    },
    defaultServing: {
      quantity: 1,
      unit: 'piece',
      grams: 150,
    },
  },
  {
    id: uuidv4(),
    name: 'Large Egg',
    category: 'Protein',
    baseUnit: 'g',
    macrosPer100: {
      calories: 155,
      protein: 13,
      carbs: 1.1,
      fat: 11,
      fiber: 0,
    },
    defaultServing: {
      quantity: 1,
      unit: 'piece',
      grams: 50,
    },
  },
  {
    id: uuidv4(),
    name: 'Whey Protein Powder',
    brand: 'Generic',
    category: 'Supplements',
    baseUnit: 'g',
    macrosPer100: {
      calories: 412,
      protein: 82,
      carbs: 8,
      fat: 8,
      fiber: 0,
    },
    defaultServing: {
      quantity: 1,
      unit: 'scoop',
      grams: 30,
    },
    isFavorite: true,
  },
  {
    id: uuidv4(),
    name: 'Banana',
    category: 'Fruits',
    baseUnit: 'g',
    macrosPer100: {
      calories: 89,
      protein: 1.1,
      carbs: 23,
      fat: 0.3,
      fiber: 2.6,
    },
    defaultServing: {
      quantity: 1,
      unit: 'piece',
      grams: 118,
    },
    isFavorite: true,
  },
  {
    id: uuidv4(),
    name: 'Brown Rice',
    category: 'Grains',
    baseUnit: 'g',
    macrosPer100: {
      calories: 370,
      protein: 7.9,
      carbs: 77,
      fat: 2.9,
      fiber: 3.5,
    },
    defaultServing: {
      quantity: 1,
      unit: 'cup',
      grams: 185,
    },
  },
  {
    id: uuidv4(),
    name: 'Greek Yogurt',
    category: 'Dairy',
    baseUnit: 'g',
    macrosPer100: {
      calories: 59,
      protein: 10,
      carbs: 3.6,
      fat: 0.4,
      fiber: 0,
    },
    defaultServing: {
      quantity: 1,
      unit: 'cup',
      grams: 245,
    },
  },
  {
    id: uuidv4(),
    name: 'Almonds',
    category: 'Nuts',
    baseUnit: 'g',
    macrosPer100: {
      calories: 579,
      protein: 21.2,
      carbs: 21.6,
      fat: 49.9,
      fiber: 12.5,
    },
    defaultServing: {
      quantity: 1,
      unit: 'cup',
      grams: 143,
    },
  },
  {
    id: uuidv4(),
    name: 'Sweet Potato',
    category: 'Vegetables',
    baseUnit: 'g',
    macrosPer100: {
      calories: 86,
      protein: 1.6,
      carbs: 20.1,
      fat: 0.1,
      fiber: 3,
    },
    defaultServing: {
      quantity: 1,
      unit: 'piece',
      grams: 130,
    },
  },
  {
    id: uuidv4(),
    name: 'Whole Milk',
    category: 'Dairy',
    baseUnit: 'ml',
    macrosPer100: {
      calories: 61,
      protein: 3.2,
      carbs: 4.8,
      fat: 3.3,
      fiber: 0,
    },
    defaultServing: {
      quantity: 1,
      unit: 'cup',
      ml: 240,
    },
    density_g_per_ml: 1.03,
  },
];
